services:
  - docker

script:
  - docker login -u $USERNAME -p $PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build --file=environment-blockci.Dockerfile --tag=sifive/environment-blockci:$TAG .
  - if [ "$TRAVIS_TAG" != "" ]; then docker push sifive/environment-blockci; fi
